//! COM interface definitions for CLR hosting and debugging.

mod clr_control;
mod clr_data;
mod clr_data_target;
mod clr_debugging;
mod clr_metahost;
mod clr_runtime_host;
mod clr_runtime_info;
mod clr_strong_name;
mod clr_task;
mod cor_debug;
mod cor_debug_appdomain;
mod cor_debug_callback;
mod cor_debug_code;
mod cor_debug_frame;
mod cor_debug_module;
mod cor_debug_process;
mod cor_debug_stepper;
mod cor_debug_thread;
mod cor_debug_value;
mod cor_profiler;
mod cor_profiler_info;
mod cor_runtime_host;
mod fusion;
mod metadata;
mod metadata_assembly;
mod metadata_emit;
mod metadata_import;
mod sos_dac;
mod xclr_data_app_domain;
mod xclr_data_assembly;
mod xclr_data_exception;
mod xclr_data_frame;
mod xclr_data_method;
mod xclr_data_module;
mod xclr_data_process;
mod xclr_data_stack_walk;
mod xclr_data_task;
mod xclr_data_type;
mod xclr_data_types;
mod xclr_data_value;

pub use clr_control::*;
pub use clr_data::*;
pub use clr_data_target::*;
pub use clr_debugging::*;
pub use clr_metahost::*;
pub use clr_runtime_host::*;
pub use clr_runtime_info::*;
pub use clr_strong_name::*;
pub use clr_task::*;
pub use cor_debug::*;
pub use cor_debug_appdomain::*;
pub use cor_debug_callback::*;
pub use cor_debug_code::*;
pub use cor_debug_frame::*;
pub use cor_debug_module::*;
pub use cor_debug_process::*;
pub use cor_debug_stepper::*;
pub use cor_debug_thread::*;
pub use cor_debug_value::*;
pub use cor_profiler::*;
pub use cor_profiler_info::*;
pub use cor_runtime_host::*;
pub use fusion::*;
pub use metadata::*;
pub use metadata_assembly::*;
pub use metadata_emit::*;
pub use metadata_import::*;
pub use sos_dac::*;
pub use xclr_data_app_domain::*;
pub use xclr_data_assembly::*;
pub use xclr_data_exception::*;
pub use xclr_data_frame::*;
pub use xclr_data_method::*;
pub use xclr_data_module::*;
pub use xclr_data_process::*;
pub use xclr_data_stack_walk::*;
pub use xclr_data_task::*;
pub use xclr_data_type::*;
pub use xclr_data_types::*;
pub use xclr_data_value::*;
